### ISSUE TITLE
Errors with TexLive 2019

### ISSUE THREAD

**Issue by nick-jhlee** [AndyClifton/CorporateLaTeX#1]
Tried to make the report_main.tex file, but got the error of "! pdfTeX error (setup): \pdfminorversion cannot be changed after data is written to the PDF file...."

My suggested fix:

1. Put "\RequirePackage{pdf14}" before "\documentclass" (report_main.tex)
2. Under makestatements, comment out "\thispagestyle{corporate}" (corporate.sty)

**Comment by AndyClifton** [comment]
I've commented the pdf14... line out in the dev version, but I need to figure out why I even included the package in the first place.

The \thispage... was included to deal with some problems when the cover page option was used. I'm leaving it in for the time being. 

I'm going to leave this issue open for the time being and will review once the package is a bit more stable.

**Comment by AndyClifton** [comment]
Seems to be fixed now.
